name: Release

on:
  push:
    tags: [v*]

jobs:
   release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true

      - name: Generate Checksum
        shell: bash
        run: |
          curl -L "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" -o ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz
          
          sha512sum *.tar.gz >> checksum.sha512
          sha512sum *.zip >> checksum.sha512
          b2sum *.tar.gz >> checksum.b2sum
          b2sum *.zip >> checksum.b2sum

      - name: Upload Checksum sha512
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./checksum.sha512
          asset_name: ${{ github.event.repository.name }}-checksum.sha512
          asset_content_type: text/plain

      - name: Upload Checksum blake2
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./checksum.b2sum
          asset_name: ${{ github.event.repository.name }}-checksum.b2sum
          asset_content_type: text/plain

      - name: Upload Static Checksum Source
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz
          asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
